import {test,expect} from '@playwright/test';
test('desktop/mobile demo, entry editing, validation, language and persistence',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1050});await page.goto('/');
 await page.getByRole('button',{name:'Utforsk en demo'}).click();
 await expect(page.getByRole('heading',{name:'Timeføring',exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.locator('.entries-panel [data-action="addTime"]').click();
 await page.locator('[name="start"]').fill('16:00');await page.locator('[name="end"]').fill('17:00');
 await page.locator('[name="desc"]').fill('<script>safe text</script>');
 await page.locator('#entry-form [type="submit"]').click();
 await expect(page.locator('.summary-total strong')).toHaveText('8,50 h');
 await expect(page.locator('.entry-description').last()).toHaveText('<script>safe text</script>');
 await page.locator('.entries-panel [data-action="addTime"]').click();
 await page.locator('[name="desc"]').fill('Overlap');
 await page.locator('#entry-form [type="submit"]').click();
 await expect(page.locator('#entry-form .form-error')).toContainText('overlapper');
 await page.keyboard.press('Escape');
 await page.locator('.sidebar [data-view="settings"]').click();
 await page.locator('[data-language]').selectOption('en');
 await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible();
 await page.locator('.sidebar [data-view="day"]').click();
 await expect(page.getByRole('heading',{name:'Time tracking',exact:true})).toBeVisible();
 await page.locator('[data-action="complete"]').click();
 await expect(page.locator('.entries-panel [data-action="addTime"]')).toBeDisabled();
 await page.locator('[data-action="reopen"]').click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await expect(page.locator('.mobile-nav')).toBeVisible();
 await page.locator('.mobile-nav [data-view="projects"]').click();
 await page.getByRole('button',{name:'Add project',exact:true}).click();
 await page.locator('[name="code"]').fill('NEW-1');await page.locator('[name="name"]').fill('New project');
 await page.locator('#project-form [type="submit"]').click();
 await expect(page.getByRole('heading',{name:'New project'})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'Explore a demo'}).click();
 await expect(page.locator('.summary-total strong')).toHaveText('8.50 h');
 await page.locator('.mobile-nav [data-view="reports"]').click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download Excel'}).click();
 expect((await download).suggestedFilename()).toBe('timelogg.xlsx');
 expect(errors).toEqual([]);
});
