import './style.css';
import * as auth from '@netlify/identity';
import {today,shift,week,hours,emptyDay,duration,total,validateDay,importLegacy} from './model.js';
import {messages} from './i18n.js';
const $=s=>document.querySelector(s), root=$('#app');
let lang=localStorage.getItem('timelogg_language')||'nb';if(!messages[lang])lang='nb';
const t=k=>messages[lang][k]||k, h=n=>hours(n,lang), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={clock:'M12 8v4l3 2 M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18',calendar:'M4 6h16v15H4z M8 3v6 M16 3v6 M4 11h16',folder:'M3 7h7l2 2h9v11H3z M3 7V4h7l2 3',report:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',plus:'M12 5v14 M5 12h14',edit:'m5 16-1 4 4-1L20 7l-3-3z M14 7l3 3',trash:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7',chevron:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6',copy:'M9 8h11v13H9z M15 8V3H4v13h5',logout:'M10 4H4v16h6 M9 12h12 M17 8l4 4-4 4',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',chat:'M3 4h18v13H8l-5 4z',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.clock}"/></svg>`;
const mountain=`<svg class="mountains" viewBox="0 0 260 130" aria-hidden="true"><defs><linearGradient id="mountain" x2="0" y2="1"><stop stop-color="#8bbcf6"/><stop offset="1" stop-color="#e6f2ff"/></linearGradient></defs><circle cx="221" cy="24" r="10" fill="#ffcc65"/><path d="M0 130 64 66l29 27 56-75 111 112" fill="url(#mountain)"/><path d="m93 93 56-75 20 40-20-15-12 29-10-7z" fill="#d8eaff"/><path d="m161 130 37-67 62 67M0 130l40-40 40 40" fill="#c9e1fc"/></svg>`;
let user=null,demo=false,days={},projects=[],selected=today(),view='day',ready=false,loading=false,loadFailed=false,authMode='login',inviteToken='',settings=null;
let pending=new Set(),saving=false,saveFailure='',generation=0,timer;
const day=()=>days[selected]||emptyDay();
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),4500);}
function dateLabel(date,options={weekday:'long',day:'numeric',month:'long',year:'numeric'}){return new Date(date+'T12:00:00').toLocaleDateString(lang==='nb'?'nb-NO':'en-GB',options);}
const brand=()=>`<a class="brand" href="#" data-action="home"><span class="brand-mark">${icon('clock')}</span><span><strong>Timelogg</strong><small>${t('tagline')}</small></span></a>`;
const language=()=>`<select class="language" aria-label="${t('language')}" data-language><option value="nb" ${lang==='nb'?'selected':''}>Norsk</option><option value="en" ${lang==='en'?'selected':''}>English</option></select>`;
const button=(action,label,ic,cls='secondary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${ic?icon(ic):''}${label}</button>`;
function render(){
 document.documentElement.lang=lang;document.title=`Timelogg · ${t('tagline')}`;
 if(!user){renderLogin();return;}
 const nav=[['day','clock'],['week','calendar'],['projects','folder'],['reports','report'],['settings','settings']];
 root.innerHTML=`<aside class="sidebar">${brand()}<nav aria-label="${t('heading')}">${nav.map(([key,ic])=>`<button data-view="${key}" class="nav-item ${view===key?'active':''}" ${view===key?'aria-current="page"':''}>${icon(ic)}<span>${t(key)}</span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="inspiration">${mountain}<p>${t('quote')}<br><strong>${t('quoteSub')}</strong></p><i></i></div><div class="private">${icon('lock')}${t('private')}</div></div></aside><div class="workspace"><header class="topbar"><div class="mobile-brand">${brand()}</div><div class="breadcrumb">${t('private')}<span>/</span>${t(view)}</div><div class="account"><span class="avatar">${esc((user.name||user.email||'T').slice(0,2).toUpperCase())}</span><span class="account-name">${esc(demo?t('demoUser'):user.name||user.email)}<small>${demo?t('demoLabel'):t('private')}</small></span>${button('logout', '', 'logout','icon-button',`aria-label="${t('logout')}" title="${t('logout')}"`)}</div></header><main><div class="page-heading"><div><span class="eyebrow">${t('tagline')}</span><h1>${t(view==='day'?'heading':view)}</h1><p>${t(view==='day'?'intro':view==='week'?'weekSub':view==='projects'?'projectSub':view==='reports'?'reportSub':'preferences')}</p></div>${['day','week'].includes(view)?`<div class="date-nav">${button('prev','', 'chevron','icon-button previous',`aria-label="${t('previous')}"`)}<label>${icon('calendar')}<input type="date" id="date-picker" aria-label="${t('chooseDate')}" value="${selected}"></label>${button('next','','chevron','icon-button',`aria-label="${t('next')}"`)}</div>`:''}</div>${demo?`<div class="demo-banner">${icon('lock')}${t('demoLabel')}</div>`:''}<div id="sync-status" role="status"></div>${loading?`<div class="empty">${t('loading')}</div>`:loadFailed?`<section class="panel empty"><p>${t('loadError')}</p>${button('reload',t('retry'),'copy')}</section>`:ready?renderView():''}</main><footer class="app-footer">Timelogg<span>${t('tagline')}</span></footer></div><nav class="mobile-nav">${nav.map(([key,ic])=>`<button data-view="${key}" class="${view===key?'active':''}" aria-label="${t(key)}">${icon(ic)}<span>${t(key)}</span></button>`).join('')}</nav><dialog id="modal"></dialog>`;
 updateSync();
}
function renderLogin(){
 const mode=authMode;const passwordMode=['login','signup','newPassword','invite'].includes(mode);
 root.innerHTML=`<div class="login-page"><header>${brand()}${language()}</header><div class="login-layout"><section class="login-story"><span class="eyebrow">TIME WELL SPENT</span><h1>${t('welcome')}</h1><p>${t('welcomeSub')}</p><div class="login-art">${mountain}<div class="art-card">${icon('clock')}<span>${t('total')}<strong>7,50 <small>h</small></strong></span><span class="check-disc">${icon('check')}</span></div></div><div class="private">${icon('lock')}${t('private')}</div></section><section class="login-card"><span class="eyebrow">TIMELOGG</span><h2>${t(mode==='invite'?'signup':mode)}</h2><p>${t('loginSub')}</p><form id="auth-form">${mode==='signup'?`<label>${t('name')}<input name="name" autocomplete="name" required maxlength="100"></label>`:''}${['login','signup','reset'].includes(mode)?`<label>${t('email')}<input name="email" type="email" autocomplete="email" required></label>`:''}${passwordMode?`<label>${t(mode==='newPassword'?'newPassword':'password')}<input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" required minlength="${mode==='login'?1:8}"></label>`:''}<p class="form-error" id="auth-message" role="alert"></p><button class="primary full" type="submit">${t(mode==='invite'?'continue':mode)}</button></form>${mode==='login'?`${button('reset',t('forgot'),null,'text-button')}<div class="divider"></div>${settings?.disableSignup?'':button('signup',t('signup'),null,'secondary full')}`:button('login',t('login'),null,'text-button full')}<div class="demo-link">${button('demo',t('demo'),'chevron','text-button')}</div></section></div><footer>Timelogg · ${t('tagline')}</footer></div>`;
}
function renderView(){if(view==='day')return renderDay();if(view==='week')return renderWeek();if(view==='projects')return renderProjects();if(view==='reports')return renderReports();return renderSettings();}
function chart(){const dates=week(selected);const max=Math.max(8,...dates.map(d=>total(days[d])));return `<div class="chart">${dates.map(d=>`<button class="chart-day ${d===selected?'selected':''}" data-date="${d}" aria-label="${esc(dateLabel(d))}: ${h(total(days[d]))}"><strong>${h(total(days[d]))}</strong><span class="bar-track"><i style="height:${Math.max(2,total(days[d])/max*100)}%"></i></span><span>${dateLabel(d,{weekday:'short'}).replace('.','')}</span></button>`).join('')}</div>`;}
function weekStats(){const dates=week(selected),sum=dates.reduce((n,d)=>n+total(days[d]),0),target=dates.slice(0,5).reduce((n,d)=>n+(days[d]?.target||7.5),0);return `<div class="week-stats"><div><small>${t('thisWeek')}</small><strong>${h(sum)} h</strong></div><div><small>${t('weekTarget')}</small><strong>${h(target)} h</strong></div><div><small>${t('remaining')}</small><strong class="green">${h(Math.max(0,target-sum))} h</strong></div></div>`;}
function renderDay(){const d=day(),locked=d.status==='complete';return `<section class="summary"><div class="summary-date">${icon('calendar')}<div><small>${selected===today()?t('today'):t('day')}</small><strong>${dateLabel(selected)}</strong><span class="badge">${t(locked?'completed':'draft')}</span></div></div><div class="summary-total">${icon('clock')}<div><small>${t('total')}</small><strong>${h(total(d))} <span>h</span></strong><small>${t('excluding')}</small></div></div><div class="summary-quote"><strong>${t('quote')}</strong><p>${t('quoteSub')}</p>${mountain}</div></section><div class="dashboard-grid"><div class="day-main">${entryPanel(false)}${entryPanel(true)}<div class="day-bottom"><label class="day-note">${icon('chat')}<textarea id="day-note" aria-label="${t('description')}" placeholder="${t('note')}" maxlength="2000" ${locked?'disabled':''}>${esc(d.note)}</textarea></label><div class="day-actions">${button('save',t('save'),null,'secondary')}${button(locked?'reopen':'complete',t(locked?'reopen':'complete'),'check','primary')}</div></div><p class="footnote">${t('fullDayHint')}</p></div><aside class="right-rail"><section class="panel"><div class="panel-heading"><h2>${t('week')}</h2><button class="text-button" data-view="week">${t('week')} ${icon('chevron')}</button></div>${chart()}${weekStats()}</section><section class="panel shortcuts"><h2>${t('shortcuts')}</h2>${button('copy',t('copy'),'copy','shortcut',locked?'disabled':'')}${button('addTime',t('addTime'),'clock','shortcut',locked?'disabled':'')}${button('addAddition',t('addAddition'),'plus','shortcut',locked?'disabled':'')}<button class="shortcut" data-view="projects">${icon('folder')}${t('seeProjects')}</button></section><div class="target-box"><label for="target">${t('target')}</label><div><input id="target" type="number" min="0.25" max="24" step="0.25" value="${d.target}" ${locked?'disabled':''}> h</div></div></aside></div>`;}
function entryPanel(addition){const entries=day().entries.filter(e=>(e.kind==='addition')===addition),locked=day().status==='complete';return `<section class="panel entries-panel"><div class="panel-heading"><div class="section-title">${icon(addition?'report':'clock')}<div><h2>${t(addition?'additions':'splits')} <span class="count">${entries.length}</span></h2><p>${t(addition?'additionsSub':'splitsSub')}</p></div></div>${button(addition?'addAddition':'addTime',t(addition?'addAddition':'addTime'),'plus','secondary',locked?'disabled':'')}</div>${entries.length?`<div class="table-head ${addition?'addition-head':''}">${(addition?['type','amount','description','wbs']:['from','to','description','wbs','hours']).map(k=>`<span>${t(k)}</span>`).join('')}<span></span></div><div class="entries">${entries.map(e=>entryRow(e,locked)).join('')}</div>`:`<div class="empty ${addition?'small-empty':''}">${addition?'':icon('clock')}<strong>${t(addition?'emptyAddition':'empty')}</strong>${addition?'':`<p>${t('emptySub')}</p>`}</div>`}${!addition&&!locked?button('addManual',t('addManual'),null,'text-button manual-link'):''}</section>`;}
function entryRow(e,locked){return `<div class="entry ${e.kind==='addition'?'addition-entry':''}">${e.kind==='addition'?`<span class="type-pill">${esc(t(e.type))}</span><strong class="addition-hours">${h(e.hours)} h</strong>`:`<div class="entry-time">${e.start?`${esc(e.start)} <span>– ${esc(e.end)}</span>`:t('manual')}</div>`}<div class="entry-description">${esc(e.desc)}</div><div class="entry-wbs">${esc(e.order||'—')}</div>${e.kind!=='addition'?`<strong class="entry-hours">${h(e.hours)} <span>h</span></strong>`:''}<div class="entry-actions">${button('edit','', 'edit','icon-button',`data-id="${esc(e.id)}" aria-label="${t('edit')}: ${esc(e.desc)}" ${locked?'disabled':''}`)}${button('delete','','trash','icon-button danger',`data-id="${esc(e.id)}" aria-label="${t('remove')}: ${esc(e.desc)}" ${locked?'disabled':''}`)}</div></div>`;}
function renderWeek(){return `<section class="panel week-panel"><div class="panel-heading"><h2>${dateLabel(week(selected)[0],{day:'numeric',month:'short'})} – ${dateLabel(week(selected)[6],{day:'numeric',month:'short'})}</h2><button class="text-button" data-date="${today()}">${t('today')}</button></div>${chart()}${weekStats()}</section><section class="panel week-list">${week(selected).map(d=>`<button data-date="${d}" class="week-row"><span><strong>${dateLabel(d,{weekday:'long'})}</strong><small>${dateLabel(d,{day:'numeric',month:'long'})}</small></span><span class="badge">${t(days[d]?.status==='complete'?'completed':'draft')}</span><strong>${h(total(days[d]))} h</strong>${icon('chevron')}</button>`).join('')}</section>`;}
function renderProjects(){const codes=[...new Set([...projects.map(p=>p.code),...Object.values(days).flatMap(d=>d.entries.map(e=>e.order)).filter(Boolean)])];return `<section class="panel"><div class="panel-heading"><h2>${t('projects')} <span class="count">${codes.length}</span></h2>${button('addProject',t('addProject'),'plus')}</div><div class="project-grid">${codes.map(code=>`<article class="project-card"><span class="project-icon">${icon('folder')}</span><span class="badge">${esc(code)}</span><h3>${esc(projects.find(p=>p.code===code)?.name||code)}</h3><p>${t('total')}</p><strong>${h(Object.values(days).flatMap(d=>d.entries).filter(e=>e.order===code&&e.kind!=='addition').reduce((s,e)=>s+e.hours,0))} h</strong></article>`).join('')||`<div class="empty">${t('noProjects')}</div>`}</div></section>`;}
function renderReports(){return `<div class="report-stats"><section class="panel"><small>${t('allTime')}</small><strong>${h(Object.values(days).reduce((s,d)=>s+total(d),0))} h</strong></section><section class="panel"><small>${t('days')}</small><strong>${Object.values(days).filter(d=>d.entries.length).length}</strong></section></div><section class="panel"><h2>${t('data')}</h2><p>${t('reportSub')}</p><div class="button-row">${button('export',t('export'),'download','primary')}${button('excel',t('excel'),'download')}</div><div class="divider"></div><h3>${t('import')}</h3><p>${t('importHelp')}</p><div class="button-row">${button('import',t('import'),'folder')}${!demo?button('legacy',t('legacy'),'copy'):''}${button('legacyLocal',t('legacyLocal'),'copy')}</div><input type="file" id="import-file" accept=".json,application/json" hidden></section>`;}
function renderSettings(){return `<section class="panel settings-panel"><div class="setting-row"><div><h2>${t('language')}</h2><p>Norsk / English</p></div>${language()}</div><div class="divider"></div><h2>${t('account')}</h2><p>${esc(user.email||t('demoUser'))}</p><p>${t('privacy')}</p><div class="button-row">${button('logout',t('logout'),'logout')}</div></section>`;}
function updateSync(){const el=$('#sync-status');if(!el)return;el.className='sync-status '+(saveFailure?'error':'');el.innerHTML=ready?`${icon(saveFailure?'clock':'check')}<span>${t(saveFailure|| (saving||pending.size?'saving':demo?'localSaved':'saved'))}</span>${saveFailure?button('save',t('retry'),null,'text-button')+button('export',t('exportFirst'),null,'text-button'):''}`:'';}
async function api(method='GET',body,path='/api/data'){await auth.refreshSession();const res=await fetch(path,{method,credentials:'same-origin',headers:{'X-Timelogg-Account':user.id,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});let result;try{result=await res.json();}catch{throw new Error('serverError');}if(!res.ok)throw new Error(result.error||'serverError');return result;}
function persistDemo(){try{localStorage.setItem('timelogg_demo',JSON.stringify({days,projects}));return true;}catch{saveFailure='saveError';toast(t('saveError'));return false;}}
function changed(){pending.add(selected);saveFailure='';clearTimeout(timer);timer=setTimeout(flush,600);updateSync();}
async function flush(){clearTimeout(timer);if(saving||!ready)return; if(demo){if(persistDemo())pending.clear();updateSync();return;}saving=true;saveFailure='';updateSync();const gen=generation;try{while(pending.size&&gen===generation){const date=pending.values().next().value;pending.delete(date);const snapshot=structuredClone(days[date]);try{const result=await api('PUT',{date,day:snapshot});if(gen!==generation)return;days[date].revision=result.revision;}catch(e){pending.add(date);throw e;}}}catch(e){saveFailure=e.message;toast(t(e.message));}finally{if(gen===generation){saving=false;updateSync();}}}
async function load(){loading=true;loadFailed=false;ready=false;render();try{const data=await api();days=data.days;projects=data.projects;ready=true;}catch{loadFailed=true;}finally{loading=false;render();}}
async function enter(u){user=u;demo=false;generation++;days={};projects=[];pending.clear();saveFailure='';saving=false;await load();}
function startDemo(){demo=true;user={id:'demo',name:t('demoUser')};try{const stored=JSON.parse(localStorage.getItem('timelogg_demo'));days=stored?.days||{};projects=stored?.projects||[];}catch{days={};projects=[];}if(!Object.keys(days).length){projects=[{code:'WBS-10023',name:lang==='nb'?'Planlegging':'Planning'},{code:'WBS-20411',name:lang==='nb'?'Produktutvikling':'Product development'},{code:'WBS-30008',name:lang==='nb'?'Kundeoppfølging':'Client relations'}];days[today()]={...emptyDay(),entries:[['08:00','10:30',lang==='nb'?'Planlegging og oppstart':'Planning and kickoff','WBS-10023'],['10:30','12:00',lang==='nb'?'Utvikling':'Development','WBS-20411'],['12:30','14:30',lang==='nb'?'Feilretting og testing':'Testing and fixes','WBS-20411'],['14:30','16:00',lang==='nb'?'Møte / oppfølging':'Meeting / follow-up','WBS-30008']].map(([start,end,desc,order])=>({id:crypto.randomUUID(),kind:'time',start,end,desc,order,hours:duration(start,end),type:''}))};persistDemo();}ready=true;loading=false;loadFailed=false;selected=today();view='day';render();}
function showModal(title,content){const modal=$('#modal');modal.innerHTML=`<div class="modal-heading"><h2>${title}</h2>${button('close','×',null,'icon-button',`aria-label="${t('close')}"`)}</div>${content}`;modal.showModal();}
function entryModal(kind='time',id){if(day().status==='complete')return;const e=day().entries.find(e=>e.id===id)||{kind,start:'08:00',end:'09:00',hours:1,desc:'',order:'',type:'travel'};kind=e.kind;showModal(t(id?'edit':kind==='addition'?'addAddition':kind==='manual'?'addManual':'addTime'),`<form id="entry-form" data-id="${esc(id||'')}" data-kind="${kind}" data-date="${selected}">${kind==='time'?`<div class="form-two"><label>${t('from')}<input type="time" name="start" required value="${esc(e.start)}"></label><label>${t('to')}<input type="time" name="end" required value="${esc(e.end)}"></label></div>`:`${kind==='addition'?`<label>${t('type')}<select name="type">${['travel','overtime','other'].map(k=>`<option value="${k}" ${k===e.type?'selected':''}>${t(k)}</option>`).join('')}</select></label>`:''}<label>${t('hours')}<input type="number" name="hours" min="0.01" max="24" step="0.01" required value="${e.hours}"></label>`}<label>${t('description')}<input name="desc" maxlength="500" required value="${esc(e.desc)}"></label><label>${t('wbs')}<input name="order" list="project-options" maxlength="100" value="${esc(e.order)}"><datalist id="project-options">${projects.map(p=>`<option value="${esc(p.code)}">${esc(p.name)}</option>`).join('')}</datalist></label><p class="form-error" role="alert"></p><div class="modal-actions">${button('close',t('cancel'),null,'secondary')}<button class="primary" type="submit">${t('save')}</button></div></form>`);}
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importData(raw){const imported=importLegacy(raw);const dates=Object.keys(imported).filter(d=>!days[d]||(!days[d].revision&&!days[d].entries.length&&!days[d].note));if(!dates.length){toast(t('noData'));return;}if(!confirm(t('importConfirm')))return;for(const date of dates){days[date]=imported[date];pending.add(date);}await flush();render();if(!saveFailure)toast(t('imported'));}
root.addEventListener('click',async event=>{const el=event.target.closest('button,a');if(!el)return;const action=el.dataset.action;if(el.dataset.view){view=el.dataset.view;render();return;}if(el.dataset.date){selected=el.dataset.date;view='day';render();return;}if(!action)return;event.preventDefault();try{
 if(action==='home'){if(user){view='day';render();}return;}
 if(['login','signup','reset'].includes(action)){authMode=action;render();return;}
 if(action==='demo'){startDemo();return;}
 if(action==='close'){$('#modal').close();return;}
 if(action==='logout'){await flush();if(pending.size||saving){toast(t('unsaved'));return;}if(!demo)await auth.logout();generation++;user=null;days={};projects=[];ready=false;demo=false;authMode='login';render();return;}
 if(action==='reload'){await load();return;}
 if(action==='prev'||action==='next'){selected=shift(selected,(action==='prev'?-1:1)*(view==='week'?7:1));render();return;}
 if(action==='addTime'||action==='addAddition'||action==='addManual'){entryModal(action==='addTime'?'time':action==='addAddition'?'addition':'manual');return;}
 if(action==='edit'){entryModal(undefined,el.dataset.id);return;}
 if(action==='delete'){if(day().status==='complete'||!confirm(t('deleteConfirm')))return;days[selected]={...day(),entries:day().entries.filter(e=>e.id!==el.dataset.id)};changed();render();return;}
 if(action==='copy'){if(day().status==='complete')return;const previous=days[shift(selected,-1)];if(!previous?.entries.length){toast(t('noData'));return;}if(!confirm(t('copyConfirm')))return;days[selected]=validateDay({...day(),entries:[...day().entries,...previous.entries.map(e=>({...e,id:crypto.randomUUID()}))]});changed();render();toast(t('copied'));return;}
 if(action==='save'){await flush();return;}
 if(action==='complete'||action==='reopen'){days[selected]={...day(),status:action==='complete'?'complete':'draft'};changed();render();await flush();return;}
 if(action==='export'){download('timelogg.json',JSON.stringify({version:2,timelogg:days,projects},null,2),'application/json');return;}
 if(action==='excel'){const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Timelogg');ws.columns=[{header:t('chooseDate'),width:14},{header:t('type'),width:24},{header:t('from'),width:10},{header:t('to'),width:10},{header:t('description'),width:45},{header:t('wbs'),width:24},{header:t('hours'),width:12}];Object.keys(days).sort().forEach(date=>days[date].entries.forEach(e=>ws.addRow([date,t(e.kind==='addition'?e.type:e.kind==='manual'?'manual':'splits'),e.start,e.end,e.desc,e.order,e.hours])));ws.getRow(1).font={bold:true};download('timelogg.xlsx',await wb.xlsx.writeBuffer(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');return;}
 if(action==='import'){$('#import-file').click();return;}
 if(action==='legacy'){await importData(await api('GET',undefined,'/api/blobs'));return;}
 if(action==='legacyLocal'){await importData({timelogg:JSON.parse(localStorage.getItem('timelogg_v1')||'{}')});return;}
 if(action==='addProject'){showModal(t('addProject'),`<form id="project-form"><label>${t('wbs')}<input name="code" required maxlength="100"></label><label>${t('projectName')}<input name="name" required maxlength="200"></label><p class="form-error" role="alert"></p><div class="modal-actions">${button('close',t('cancel'))}<button class="primary" type="submit">${t('save')}</button></div></form>`);}
 }catch(e){toast(t(e.message));}
});
root.addEventListener('change',async event=>{const el=event.target;if(el.matches('[data-language]')){lang=el.value;localStorage.setItem('timelogg_language',lang);render();}else if(el.id==='date-picker'){if(el.value){selected=el.value;render();}}else if(el.id==='target'){try{days[selected]=validateDay({...day(),target:Number(el.value)});changed();render();}catch(e){toast(t(e.message));el.value=day().target;}}else if(el.id==='import-file'){try{const file=el.files[0];if(file){if(file.size>5000000)throw new Error('invalidDay');await importData(JSON.parse(await file.text()));}}catch(e){toast(t(messages[lang][e.message]?e.message:'invalidDay'));}el.value='';}});
root.addEventListener('input',event=>{if(event.target.id==='day-note'&&day().status!=='complete'){days[selected]={...day(),note:event.target.value};changed();}});
root.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form)),submit=form.querySelector('[type="submit"]');submit.disabled=true;const error=form.querySelector('.form-error');if(error)error.textContent='';try{
 if(form.id==='auth-form'){
  if(authMode==='reset'){await auth.requestPasswordRecovery(values.email);$('#auth-message').textContent=t('emailSent');return;}
  if(authMode==='newPassword'){await auth.updateUser({password:values.password});authMode='login';await enter(await auth.getUser());toast(t('passwordUpdated'));return;}
  if(authMode==='invite'){await enter(await auth.acceptInvite(inviteToken,values.password));return;}
  if(authMode==='signup'){await auth.signup(values.email,values.password,{full_name:values.name});const u=await auth.getUser();if(u)await enter(u);else $('#auth-message').textContent=t('emailSent');return;}
  await enter(await auth.login(values.email,values.password));return;
 }
 if(form.id==='entry-form'){
  const date=form.dataset.date,kind=form.dataset.kind,id=form.dataset.id||crypto.randomUUID();const entry={...values,id,kind,hours:kind==='time'?duration(values.start,values.end):Number(values.hours)};
  const d=days[date]||emptyDay();const entries=d.entries.some(e=>e.id===id)?d.entries.map(e=>e.id===id?entry:e):[...d.entries,entry];days[date]=validateDay({...d,entries});selected=date;changed();$('#modal').close();render();return;
 }
 if(form.id==='project-form'){const project={code:values.code.trim(),name:values.name.trim()};if(!project.code||!project.name)throw new Error('invalidText');if(!demo)await api('POST',project);projects=[...projects.filter(p=>p.code!==project.code),project];if(demo)persistDemo();$('#modal').close();render();}
 }catch(e){if(error)error.textContent=t(form.id==='auth-form'?'authError':e.message);}finally{submit.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(pending.size||saving){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>{if(pending.size)flush();});
window.addEventListener('storage',event=>{if(!demo && event.key==='gotrue.user' && !event.newValue){generation++;user=null;days={};projects=[];pending.clear();ready=false;render();}});
render();
try{const callback=await auth.handleAuthCallback();if(callback?.type==='recovery'){authMode='newPassword';render();}else if(callback?.type==='invite'){inviteToken=callback.token;authMode='invite';render();}else{const u=await auth.getUser();if(u)await enter(u);}}catch{toast(t('authError'));}
auth.getSettings().then(s=>{settings=s;if(!user)render();}).catch(()=>{if(!user&&$('#auth-message'))$('#auth-message').textContent=t('authUnavailable');});
